### ISSUE TITLE
Spaces in multiline strings

### ISSUE THREAD

**Issue by ambs** [xenoterracide/Dist-Zilla-Plugin-Test-EOL#2]
Hey

I am not sure the relevance of checking for whitespaces in the end of multiline strings. One might want them, really.
A flag option?

I know that is not easy to implement without parsing the file, but...

Cheers
ambs

**Comment by xenoterracide** [comment]
are you perhaps talking about the `trailing_whitespace` option provided by Test::EOL? which there's already an option for?

**Comment by ambs** [comment]
right, trailing_whitespace can be used to check/don't check for whitespaces at the end of lines. But I did not find anything to turn off this check inside strings.

But you are right, probably I should request that to Test::EOL authors, right?

**Comment by xenoterracide** [comment]
yeah  I'd check with them, if they add a feature, then I'll work on adding it here.
