### ISSUE TITLE
Please merge with Dist::Zilla::Plugin::EOLTests

### ISSUE THREAD

**Issue by karenetheridge** [xenoterracide/Dist-Zilla-Plugin-Test-EOL#3]
This dist should be merged with Dist::Zilla::Plugin::EOLTests so the namespace can be shared - it doesn't make much sense for two dists to exist that do the same thing.

EOLTests can be patched to restrict the tests to AUTHOR_TESTING.

**Comment by xenoterracide** [comment]
you could merge the other way... since ::Test:: is the improved namespacing....

**Comment by karenetheridge** [comment]
On Mon, Feb 11, 2013 at 01:37:31PM -0800, Caleb Cushing wrote:

> you could merge the other way... since ::Test:: is the improved namespacing....

I can't speak for everyone, but I'd be fine with that if you granted
comaint to everyone who currently has comaint of [EOLTests].

**Comment by xenoterracide** [comment]
I'm not seeing the benefit here. To have one it would seem they'd have to share code... I mean there's the hit by a bus benefit I suppose... I'll do this if patches arise that allow them to share code. So everyone can have the test the way they want it.

**Comment by karenetheridge** [comment]
@xenoterracide hey, are you still involved with perl?  I'd be happy to carry through with the merging effort.

what I'd do is:
- unite [Test::EOL] and [EOLTests] into a common dist, Dist-Zilla-Plugin-Test-EOL, sharing code (EOLTests being a wrapper that called into [Test::EOL] with a deprecation statement - just as [NoTabsTests] does)
- everyone with permissions on either of those dists would get perms on the new version (it might be fair to give rafl first-come, since he's the true author)
- use a common version that is higher than all previous versions
- keep the default values of each existing plugin - [EOLTests] would default to using xt/release, [Test::EOL] would default to using xt/author, but have a config option so authors can choose what they like (I did this recently in [Test::NoTabs]/[NoTabsTests])
- ...
- profit!

**Comment by xenoterracide** [comment]
sounds fine, I don't really have much of an opinion anymore since I'm less and less involved with Perl these days. just let me know the CPAN id's I need to allow on PAUSE once you've done the work.

**Comment by karenetheridge** [comment]
super, sounds good! I hope to get to this in the next few weeks.

**Comment by dolmen** [comment]
Cc: @dolmen

**Comment by karenetheridge** [comment]
I've combined the modules into one dist -- see https://github.com/karenetheridge/Dist-Zilla-Plugin-Test-EOL/tree/topic/reunification -- which I can release as version 0.13.

My PAUSE id is ETHER -- I think we should add as comaint everyone who has comaint on either of the modules -- so perhaps the easiest thing to do is to give first-come to @rafl (FLORA) and have him give comaint to everyone else?

**Comment by xenoterracide** [comment]
sorry, kept forgetting about this. done

**Comment by karenetheridge** [comment]
On Tue, Oct 21, 2014 at 06:15:38AM -0700, Caleb Cushing wrote:

> sorry, kept forgetting about this. done

Excellent, thanks, I'll ship the reunification release tonight!  \o/
