### ISSUE TITLE
This module is impossible to find in a search for "Dist::Zilla" and "trailing space" or "trailing whitespace" (even without the quotes)

### ISSUE THREAD

**Issue by shlomif** [xenoterracide/Dist-Zilla-Plugin-Test-EOL#4]
Hi @xenoterracide ,

this MetaCPAN search - https://metacpan.org/search?q=dist%3A%3Azilla%20trailing%20whitespace does not find this module and neither does this one - https://metacpan.org/search?q=dist%3A%3Azilla+trailing+space . The problem is caused by the fact that there are only the keywords of "trailing_whitespace" in the file, and the underscore throws the MetaCPAN search off.

This misled me to believe such a plugin was not available for Dist-Zilla, which caused the filing of this bug:

https://rt.cpan.org/Public/Bug/Display.html?id=89422

Regards,

-- Shlomi Fish

**Comment by xenoterracide** [comment]
I've gotta finish moving today, but if you wanted to send a doc patch that'd be cool.

**Comment by shlomif** [comment]
Fixed on 0.19 with my changes there. Closing this issue.
